package net.pyraetos.engine;;

/**
 * Created by Denise on 3/28/2017.
 */
public enum Packets {
    LOGIN, DISCONNECT, UPDATE, ACTION,
    LOGIN_RESPONSE, ACTION_CONFIRM, UPDATE_CONFIRM,
    SERVER_DISCONNECT, OTHER_PLAYER_LOGIN, OTHER_PLAYER_DISCONNECT, OTHER_PLAYER_UPDATE, OTHER_PLAYER_ACTION
}
